apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
  #namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: user-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: rajivbansal2981/user-service:0.0.1-RELEASE
        imagePullPolicy: Always #IfNotPresent
        ports:
          - name: http
            containerPort: 3379 # The port that the container exposes
          - name: multicast
            containerPort: 5701 # The port that Hazelcast exposes
        env:
        - name: DB_HOSTNAME
          valueFrom:
             configMapKeyRef:
              name: user-service-configmap
              key: database.hostname #MySQL db host name
        - name: DB_NAME
          valueFrom: 
             configMapKeyRef:
                 name: user-service-configmap
                 key: database.name
        - name: DB_USERNAME
          valueFrom: 
             configMapKeyRef:
                 name: user-service-configmap
                 key: database.username
        - name: DB_PASSWORD
          valueFrom:
             secretKeyRef:
                name: user-service-secrets
                key: database.password
        - name: DB_PORT
          valueFrom: 
             configMapKeyRef:
                 name: user-service-configmap
                 key: database.port
        - name: SPRING_ACTIVE_PROFILE
          valueFrom: 
             configMapKeyRef:
                 name: user-service-configmap
                 key: spring.active.profile
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels: #PODS
    app: user-service
  namespace: default
spec:
  type: ClusterIP #NodePort or LoadBalancer or ClusterIP
  selector:
    app: user-service
  ports:
   - name: hazelcast
     port: 5701
   - name: app
     port: 3379